/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author TOSHIBA DC
 */
public class gantipassword extends javax.swing.JInternalFrame {
    
    String nama = login.getU_nama();
    Connection conn;
    Statement st;
    ResultSet rs;

    /**
     * Creates new form murid
     */
     private String a,b;
    private int c;
    public gantipassword() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
       
        userJL.setText(nama);
        jLabel7.setVisible(false);
        confirmBT.setVisible(false);
        tampungJl.setVisible(false);
       visibleBtn(false);
    
    }
    public void tampilUser(String user){
        userJL.setText(user);
    }
 private void visibleBtn(boolean a){
        verifikasBt.setVisible(!a);
        changeBT.setVisible(a);
        jLabel5.setVisible(!a);
        jLabel6.setVisible(a);
        jlblKet.setVisible(a);
        jlblKet1.setVisible(a);
    }
 private void gantiPass(){
        try {
            setKoneksi();
            String sql="update admin set "+
                "password = "+"'"+passTF.getText()+"' "+
                "where nama = '"+userJL.getText()+"'";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Password Berhasil Diubah","Koneksi Sukses",JOptionPane.INFORMATION_MESSAGE);
            conn.close();
            passTF.setText("");
            visibleBtn(false);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Gagal mengubah password");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userJL = new javax.swing.JLabel();
        passTF = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlblKet = new javax.swing.JLabel();
        confirmBT = new javax.swing.JButton();
        jlblKet1 = new javax.swing.JLabel();
        verifikasBt = new javax.swing.JButton();
        changeBT = new javax.swing.JButton();
        tampungJl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        helpLB = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setPreferredSize(new java.awt.Dimension(1080, 680));
        setVerifyInputWhenFocusTarget(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Masukkan Password Lama Anda");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Masukkan Password Baru Anda");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Masukkan Kembali Password Baru Anda");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nama         :");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Password  :");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, 40));

        userJL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.add(userJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 220, 40));

        passTF.setBorder(null);
        passTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTFActionPerformed(evt);
            }
        });
        jPanel5.add(passTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 210, 40));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 300, 10));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 290, 10));

        jlblKet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblKet.setForeground(new java.awt.Color(255, 0, 0));
        jlblKet.setText("Panjang karakter password tidak boleh kurang dari 2 digit");
        jlblKet.setAutoscrolls(true);
        jPanel5.add(jlblKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        confirmBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confirmBT.setText("OK");
        confirmBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmBTMouseEntered(evt);
            }
        });
        confirmBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBTActionPerformed(evt);
            }
        });
        jPanel5.add(confirmBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, 30));

        jlblKet1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblKet1.setForeground(new java.awt.Color(255, 0, 0));
        jlblKet1.setText("dan tidak boleh lebih dari 10 digit !");
        jPanel5.add(jlblKet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        verifikasBt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        verifikasBt.setText("OK");
        verifikasBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verifikasBtMouseEntered(evt);
            }
        });
        verifikasBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifikasBtActionPerformed(evt);
            }
        });
        jPanel5.add(verifikasBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, 30));

        changeBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        changeBT.setText("OK");
        changeBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeBTMouseEntered(evt);
            }
        });
        changeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBTActionPerformed(evt);
            }
        });
        jPanel5.add(changeBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, 30));
        jPanel5.add(tampungJl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 10, 0));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 463, 395));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpLB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        helpLB.setForeground(new java.awt.Color(255, 255, 255));
        helpLB.setText("GANTI PASSWORD");
        jPanel4.add(helpLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 38));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1070, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBTActionPerformed
        // TODO add your handling code here:
         a = tampungJl.getText();
        b = passTF.getText();

        if (a.equals(b)) {
            c = JOptionPane.showConfirmDialog(null, "Anda yakin ingin merubah password?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
            if (c == 0){
                gantiPass();
                jLabel7.setVisible(false);
                confirmBT.setVisible(false);
            }
            else
            {
                visibleBtn(false);
                passTF.setText("");
                jLabel7.setVisible(false);
                confirmBT.setVisible(false);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Password baru yang anda masukkan tidak cocok!");
            passTF.setText("");
            passTF.requestFocus();
        }
    }//GEN-LAST:event_confirmBTActionPerformed

    private void verifikasBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifikasBtActionPerformed
        // TODO add your handling code here:
        try {
            setKoneksi();
            String sql="select * from admin where nama = '"+
            userJL.getText()+"' and password = '"+passTF.getText()+"'";
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()) {
                passTF.setText("");
                visibleBtn(true);
            }
            else  {
                passTF.setText("");
                JOptionPane.showMessageDialog(null, "Password lama yang anda masukkan salah!");
                visibleBtn(false);
                passTF.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Gagal");
        }
    }//GEN-LAST:event_verifikasBtActionPerformed

    private void changeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBTActionPerformed
        // TODO add your handling code here:
        
       if(passTF.getText().length()<2) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh kurang dari 2 digit !");
            passTF.setText("");
            visibleBtn(true);
            passTF.requestFocus();
        }
        else if(passTF.getText().length()>10) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh lebih dari 10 digit !");
            passTF.setText("");
            visibleBtn(true);
            passTF.requestFocus();
        }
        else {
            b = passTF.getText();
            a = b;
            tampungJl.setText(a);
            passTF.setText("");
            jLabel7.setVisible(true);
            confirmBT.setVisible(true);

            visibleBtn(false);
            verifikasBt.setVisible(false);
            jLabel5.setVisible(false);
        
    }       
    }//GEN-LAST:event_changeBTActionPerformed

    private void verifikasBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verifikasBtMouseEntered
        // TODO add your handling code here:
        verifikasBt.setBackground(new Color(204,145,226));
        verifikasBt.setForeground(Color.black);
    }//GEN-LAST:event_verifikasBtMouseEntered

    private void changeBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBTMouseEntered
        // TODO add your handling code here:\
         changeBT.setBackground(new Color(204,145,226));
        changeBT.setForeground(Color.black);
    }//GEN-LAST:event_changeBTMouseEntered

    private void confirmBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmBTMouseEntered
        // TODO add your handling code here:
        confirmBT.setBackground(new Color(204,145,226));
        confirmBT.setForeground(Color.black);
    }//GEN-LAST:event_confirmBTMouseEntered

    private void passTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeBT;
    private javax.swing.JButton confirmBT;
    private javax.swing.JLabel helpLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlblKet;
    private javax.swing.JLabel jlblKet1;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JLabel tampungJl;
    private javax.swing.JLabel userJL;
    private javax.swing.JButton verifikasBt;
    // End of variables declaration//GEN-END:variables
public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/inventory","root","");
            st=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return conn; 
    }
}
