/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;

/**
 *
 * @author TOSHIBA DC
 */
public class menu extends javax.swing.JFrame {
     String nama = login.getU_nama();

    /**
     * Creates new form spp
     */
    public menu() {
        initComponents();
        userJL.setText(nama);
        setIcon();
       
        jamtanggal();
    }
    public void hakAksesPemilik(){
        
    }
    
    public void hakAksespetugas(){
         btn_home.setEnabled(false);
        petugas.setEnabled(false);
        
       barang.setEnabled(false);
         btn_barang.setEnabled(false);
        
        
    }
    
    public void hakAksesPersediaan(){
        btn_home.setEnabled(false);
        btn_keluar.setEnabled(false);
         btn_masuk.setEnabled(false);
          masuk.setEnabled(false);
        keluar.setEnabled(false);
        supplier.setEnabled(false);
        laporanmasuk.setEnabled(false);
        laporankeluar.setEnabled(false);
         petugas.setEnabled(false);
       
       
    }
 private void setIcon() {
          ImageIcon img = new ImageIcon("src/gambar/kredit.png");
        setIconImage(img.getImage());
    }
     private void jamtanggal() {
           DateFormat tgl=new SimpleDateFormat("dd MMMM yyyy");
        DateFormat waktu=new SimpleDateFormat("HH:mm:ss");
        String htgl=tgl.format(Calendar.getInstance().getTime());
        String hwaktu=waktu.format(Calendar.getInstance().getTime());
        loginJL.setText(htgl+" - "+hwaktu); 
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_barang = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        btn_masuk = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userJL = new javax.swing.JLabel();
        loginJL = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        dp = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Exit = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        barang = new javax.swing.JMenuItem();
        supplier = new javax.swing.JMenuItem();
        petugas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        masuk = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenuItem();
        laporanbarang = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        laporanmasuk = new javax.swing.JMenuItem();
        laporankeluar = new javax.swing.JMenuItem();
        gantipassword = new javax.swing.JMenu();
        password = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cv Anugerah Berkah ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jl Palapa Raya No 32");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 10));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-home-24.png"))); // NOI18N
        btn_home.setText("HOME");
        btn_home.setContentAreaFilled(false);
        btn_home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
        });
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel4.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 216, 60));

        btn_barang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/barang.png"))); // NOI18N
        btn_barang.setText("DATA BARANG");
        btn_barang.setContentAreaFilled(false);
        btn_barang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_barangMouseEntered(evt);
            }
        });
        btn_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_barangActionPerformed(evt);
            }
        });
        jPanel4.add(btn_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 60));

        btn_keluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Tambah.png"))); // NOI18N
        btn_keluar.setText("BARANG KELUAR");
        btn_keluar.setContentAreaFilled(false);
        btn_keluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_keluarMouseEntered(evt);
            }
        });
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 216, 60));

        btn_logout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cancel.png"))); // NOI18N
        btn_logout.setText("LOGOUT");
        btn_logout.setContentAreaFilled(false);
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
        });
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel4.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 216, 60));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, -1));
        jPanel4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, -1));
        jPanel4.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, -1));
        jPanel4.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, -1));

        btn_masuk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_masuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Tambah.png"))); // NOI18N
        btn_masuk.setText("BARANG MASUK");
        btn_masuk.setContentAreaFilled(false);
        btn_masuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_masukMouseEntered(evt);
            }
        });
        btn_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukActionPerformed(evt);
            }
        });
        jPanel4.add(btn_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 130, 220, 60));
        jPanel4.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 240, 330));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo unindra.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 760));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplikasi  Inventory Barang");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 11, 341, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Management System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 47, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("WELOCOME     :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TANGGAL          :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        userJL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userJL.setForeground(new java.awt.Color(255, 255, 255));
        userJL.setText("Q");
        jPanel2.add(userJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 290, 30));

        loginJL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginJL.setForeground(new java.awt.Color(255, 255, 255));
        loginJL.setText("Q");
        jPanel2.add(loginJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 290, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1080, 80));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 122, 40, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        dp.setBackground(new java.awt.Color(204, 204, 255));
        dp.setForeground(new java.awt.Color(204, 204, 255));
        dp.setDoubleBuffered(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 270, 10));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL BARANG KELUAR");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        jTextField3.setBackground(new java.awt.Color(0, 102, 102));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jTextField3.setBorder(null);
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, 60));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 270, 140));

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 270, 10));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JUMLAH BARANG");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 20));

        jTextField1.setBackground(new java.awt.Color(51, 102, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jTextField1.setBorder(null);
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, 60));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 270, 140));

        jPanel7.setBackground(new java.awt.Color(255, 0, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 270, 10));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TOTAL BARANG MASUK");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        jTextField2.setBackground(new java.awt.Color(255, 0, 51));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jTextField2.setBorder(null);
        jPanel7.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, 60));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 270, 140));

        dp.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 1080, 680));

        Exit.setText("File");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        Exit.add(exit);

        jMenuBar1.add(Exit);

        jMenu2.setText("Data Master");

        barang.setText("Data Barang");
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });
        jMenu2.add(barang);

        supplier.setText("Data Supplier");
        supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierActionPerformed(evt);
            }
        });
        jMenu2.add(supplier);

        petugas.setText("Data Petugas");
        petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petugasActionPerformed(evt);
            }
        });
        jMenu2.add(petugas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Data Transaksi");

        masuk.setText("Transaksi Masuk");
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });
        jMenu3.add(masuk);

        keluar.setText("Transaksi Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenu3.add(keluar);

        jMenuBar1.add(jMenu3);

        laporanbarang.setText("Laporan");

        jMenuItem1.setText("Laporan Barang");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        laporanbarang.add(jMenuItem1);

        laporanmasuk.setText("Laporan Masuk");
        laporanmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanmasukActionPerformed(evt);
            }
        });
        laporanbarang.add(laporanmasuk);

        laporankeluar.setText("Laporan Keluar");
        laporankeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporankeluarActionPerformed(evt);
            }
        });
        laporanbarang.add(laporankeluar);

        jMenuBar1.add(laporanbarang);

        gantipassword.setText("Peraturan");

        password.setText("Ganti Password");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        gantipassword.add(password);

        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        gantipassword.add(jMenuItem2);

        jMenuBar1.add(gantipassword);

        jMenu7.setText("About");

        jMenuItem3.setText("Tentang Aplikasi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barangActionPerformed
        // TODO add your handling code here:
        
         barang b= new barang();
       dp.add(b);
       admin d = new admin();
       dp.remove(d);
        b.setVisible(true);
    }//GEN-LAST:event_btn_barangActionPerformed

    private void btn_barangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseEntered
        // TODO add your handling code here:
        
        btn_barang.setBackground(new Color(204,145,226));
        btn_barang.setForeground(Color.black);
    }//GEN-LAST:event_btn_barangMouseEntered

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
         btn_home.setBackground(new Color(204,145,226));
        btn_home.setForeground(Color.black);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_masukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseEntered
        // TODO add your handling code here:
         btn_masuk.setBackground(new Color(204,145,226));
        btn_masuk.setForeground(Color.black);
    }//GEN-LAST:event_btn_masukMouseEntered

    private void btn_keluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluarMouseEntered
        // TODO add your handling code here:
         btn_keluar.setBackground(new Color(204,145,226));
        btn_keluar.setForeground(Color.black);
    }//GEN-LAST:event_btn_keluarMouseEntered

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
         btn_logout.setBackground(new Color(204,145,226));
        btn_logout.setForeground(Color.black);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
         menu a = new menu();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masukActionPerformed
        // TODO add your handling code here:
        masuk m= new masuk();
       dp.add(m);
       admin d = new admin();
       dp.remove(d);
        m.setVisible(true);
    }//GEN-LAST:event_btn_masukActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        keluar b= new keluar();
       dp.add(b);
       admin d = new admin();
       dp.remove(d);
        b.setVisible(true);
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
         keluar k= new keluar();
       dp.add(k);
       admin d = new admin();
       dp.remove(d);
        k.setVisible(true);
    }//GEN-LAST:event_keluarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         laporanbarang k= new laporanbarang();
       dp.add(k);
       admin d = new admin();
       dp.remove(d);
        k.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void laporanmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanmasukActionPerformed
        // TODO add your handling code here:
        laporanmasuk b= new laporanmasuk();
       dp.add(b);
       admin d = new admin();
       dp.remove(d);
        b.setVisible(true);
    }//GEN-LAST:event_laporanmasukActionPerformed

    private void laporankeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporankeluarActionPerformed
        // TODO add your handling code here:
        laporankeluar b= new laporankeluar();
       dp.add(b);
       admin d = new admin();
       dp.remove(d);
        b.setVisible(true);
    }//GEN-LAST:event_laporankeluarActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        login h=new login();
        h.setLocationRelativeTo(null);
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        login h=new login();
        h.setLocationRelativeTo(null);
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        // TODO add your handling code here:
         barang b= new barang();
       dp.add(b);
       admin d = new admin();
       dp.remove(d);
        b.setVisible(true);
    }//GEN-LAST:event_barangActionPerformed

    private void supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierActionPerformed
        // TODO add your handling code here:
         supplier s= new supplier();
       dp.add(s);
       admin d = new admin();
       dp.remove(d);
        s.setVisible(true);
    }//GEN-LAST:event_supplierActionPerformed

    private void petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugasActionPerformed
        // TODO add your handling code here:
         petugas p= new petugas();
       dp.add(p);
       admin d = new admin();
       dp.remove(d);
        p.setVisible(true);
    }//GEN-LAST:event_petugasActionPerformed

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        // TODO add your handling code here:
         masuk m= new masuk();
       dp.add(m);
       admin d = new admin();
       dp.remove(d);
        m.setVisible(true);
    }//GEN-LAST:event_masukActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         help h= new help();
       dp.add(h);
       admin d = new admin();
       dp.remove(d);
        h.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
        gantipassword gp= new gantipassword();
       dp.add(gp);
       admin d = new admin();
       dp.remove(d);
        gp.setVisible(true);
    }//GEN-LAST:event_passwordActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        tentangaplikasi gp= new tentangaplikasi();
       dp.add(gp);
       admin d = new admin();
       dp.remove(d);
        gp.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Exit;
    private javax.swing.JMenuItem barang;
    private javax.swing.JButton btn_barang;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_masuk;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu gantipassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JMenu laporanbarang;
    private javax.swing.JMenuItem laporankeluar;
    private javax.swing.JMenuItem laporanmasuk;
    private javax.swing.JLabel loginJL;
    private javax.swing.JMenuItem masuk;
    private javax.swing.JMenuItem password;
    private javax.swing.JMenuItem petugas;
    private javax.swing.JMenuItem supplier;
    private javax.swing.JLabel userJL;
    // End of variables declaration//GEN-END:variables
}
